OPENEUROPA-2943: Upgrade php to 7.3.
openeuropa/config_owner pull request #13
Opened 2020-03-19 17:20 UTC by sergepavle

## OPENEUROPA-[Insert ticket number here]

### Description

[Insert description here]

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2020-03-24 13:38 UTC, nagyad requested changes
Please change the version in the info.yml:5
It defines the minimum version of php required for the module.

2020-03-24 13:43 UTC, nagyad submitted a review, later dismissed

2020-03-26 08:18 UTC, 22Alexandra approved these changes

2020-03-26 16:52 UTC, imanoleguskiza approved these changes

2020-03-30 13:09 UTC, merged