OPENEUROPA-1355
openeuropa/config_owner pull request #4
Opened 2018-12-18 12:42 UTC by upchuk

## OPENEUROPA-1355

### Description

* Fixed the optional config in the test (using config entities instead of simple config which cannot be optional)
* Made sure that new config (that doesnt yet exist in the site active or sync storage) is picked up if it's owned and can be imported (and then exported)

### Change log

- Added:
- Changed:
- Deprecated:
- Removed:
- Fixed:
- Security:

### Commands

```sh
[Insert commands here]

```

2019-03-25 08:39 UTC, ademarco submitted a review, later dismissed

2019-04-01 14:01 UTC, dxvargas requested changes

2019-04-01 14:01 UTC, dxvargas commented on src/Plugin/ConfigFilter/ConfigOwner.php
> +      if ($prefix !== '' && ($prefix === "" || strpos($name, $prefix) === 0)) {
Adding `$prefix === ""` in conjunction doesn't make any difference.
If `$prefix === ''` the all condition was already false and it will still be.
If `$prefix !== ''`  the all condition was only dependent of `strpos($name, $prefix) === 0` and it will still be.
So new code is doing nothing.

2019-04-01 14:01 UTC, dxvargas commented on src/Plugin/ConfigFilter/ConfigOwner.php
> +    // sync storage doesn't really matter. What counts is the original owned
`sync` change should also be done in method's doc block, where we still read `staging`.

2019-04-01 14:01 UTC, dxvargas commented on tests/modules/config_owner_test/config_owner_test.owned_config.yml
> +    views.view.config_owner_test_view_one: ~
Missing new line.

2019-04-01 14:01 UTC, dxvargas commented on tests/modules/config_owner_test/config/schema/config_owner_test.schema.yml
> +      label: 'Name'
Missing new line.

2019-04-01 14:01 UTC, dxvargas commented on tests/modules/config_owner_test/config/install/config_owner_test.new.yml
> +name: This config is owned but does not yet exist in the site's sync storage.
Missing new line

2019-04-05 08:41 UTC, dxvargas approved these changes

2019-05-02 06:40 UTC, ademarco approved these changes

2019-05-02 06:41 UTC, merged